//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: D:\Java\git\core-ios-widgets\IOSChipPlugin\src\main\java\com\ashera\chip\ChipPlugin.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ChipPlugin")
#ifdef RESTRICT_ChipPlugin
#define INCLUDE_ALL_ChipPlugin 0
#else
#define INCLUDE_ALL_ChipPlugin 1
#endif
#undef RESTRICT_ChipPlugin

#if !defined (ASChipPlugin_) && (INCLUDE_ALL_ChipPlugin || defined(INCLUDE_ASChipPlugin))
#define ASChipPlugin_

@interface ASChipPlugin : NSObject

#pragma mark Public

- (instancetype)init;

+ (void)initPlugin OBJC_METHOD_FAMILY_NONE;

@end

J2OBJC_EMPTY_STATIC_INIT(ASChipPlugin)

FOUNDATION_EXPORT void ASChipPlugin_init(ASChipPlugin *self);

FOUNDATION_EXPORT ASChipPlugin *new_ASChipPlugin_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ASChipPlugin *create_ASChipPlugin_init(void);

FOUNDATION_EXPORT void ASChipPlugin_initPlugin(void);

J2OBJC_TYPE_LITERAL_HEADER(ASChipPlugin)

@compatibility_alias ComAsheraChipChipPlugin ASChipPlugin;

#endif

#pragma pop_macro("INCLUDE_ALL_ChipPlugin")
